spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/riot-app-database
    username: postgres
    password: alamakota123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false # If you're using Liquibase, set this to true

riot:
  api:
    header: ${API_HEADER}
    token: ${API_TOKEN}